name: image-lab
channels:
  - conda-forge
  - defaults
dependencies:
# use specific Python version to avoid possible incompatibilities
  - python=3.8
  - streamlit=0.76.0
  - scikit-image=0.18.1
  - matplotlib=3.3.4
# linting and testing
# better to pin the versions so that we do not get "surprises"
# and sometimes update the packages so we are up to date
  - flake8=3.8.4
  - pep8-naming=0.11.1
  - pytest=6.2.0
# black for automatic code formatting
  - black
  - flake8-black=0.2.1
